"use client";

import { useState } from "react";
import { getAllPrimitives, type PrimitiveDefinition } from "@/platform/primitives/registry";
import { PrimitiveRenderer } from "@/components/capability/PrimitiveRenderer";
import type { ResolvedPrimitive } from "@/platform/primitives/resolver";
import { ArrowLeft, ChevronDown, ChevronRight } from "lucide-react";
import Link from "next/link";

import "@/platform/primitives/registry";

// ─── Mock primitives for preview ───
const PREVIEW_PRIMITIVES: Record<string, ResolvedPrimitive> = {
  'banner': { type: 'banner', location: 'global', params: { title: 'Drift detected', message: 'Writing has diverged from the outline in 3 places.', severity: 'warning' } },
  'node-icon': { type: 'node-icon', location: 'outline-node', params: { nodeId: 'sec-1', status: 'partial', tooltip: '2 of 4 intents covered' } },
  'node-badge': { type: 'node-badge', location: 'outline-node', params: { nodeId: 'sec-1', label: 'modified', variant: 'modified' } },
  'section-alert': { type: 'section-alert', location: 'outline-node', params: { sectionId: 'sec-2', title: 'Cross-section conflict', message: 'Your changes conflict with Bob\'s Method section.', severity: 'warning' } },
  'summary-bar': { type: 'summary-bar', location: 'outline-node', params: { level: 'partial', counts: '{"covered":3,"partial":2,"missing":1}' } },
  'sentence-highlight': { type: 'sentence-highlight', location: 'writing-editor', params: { startAnchor: 'Collaborative writing is one of the most...', color: 'yellow', tooltip: 'Partially covers intent about team coordination' } },
  'issue-dot': { type: 'issue-dot', location: 'writing-editor', params: { anchor: 'This negotiation is the essence...', type: 'orphan', index: '1', detail: 'No matching intent' } },
  'inline-widget': { type: 'inline-widget', location: 'writing-editor', params: { variant: 'suggestion', content: 'Consider adding content about real-time synchronization challenges.', intentRef: 'sec-1-2' } },
  'ai-marker': { type: 'ai-marker', location: 'writing-editor', params: { startAnchor: 'This paragraph was generated by AI...' } },
  'result-list': { type: 'result-list', location: 'right-panel', params: { title: 'Method Section', badge: 'significant', badgeVariant: 'warning', detail: 'Changing the research question will affect the system design rationale.' } },
  'diff-view': { type: 'diff-view', location: 'right-panel', params: { before: 'The system uses a centralized architecture for real-time sync.', after: 'The system uses a distributed architecture with conflict-free replicated data types.', mode: 'side-by-side' } },
  'action-group': { type: 'action-group', location: 'right-panel', params: { actions: JSON.stringify([{ label: 'Propose Change', action: 'propose', variant: 'primary' }, { label: 'Dismiss', action: 'dismiss', variant: 'default' }]) } },
  'text-input': { type: 'text-input', location: 'right-panel', params: { label: 'What changed and why?', placeholder: 'Explain your reasoning...', action: 'set-reasoning', rows: '2' } },
  'comment-thread': { type: 'comment-thread', location: 'right-panel', params: { author: 'Alice', action: 'approve', text: 'Looks good, the new framing is clearer.' } },
  'progress-bar': { type: 'progress-bar', location: 'right-panel', params: { current: '3', total: '5', label: '3/5 approved', variant: 'success' } },
};

export default function FoundationPage() {
  const primitives = getAllPrimitives();

  // Group by location
  const byLocation: Record<string, PrimitiveDefinition[]> = {};
  for (const p of primitives) {
    if (!byLocation[p.location]) byLocation[p.location] = [];
    byLocation[p.location].push(p);
  }

  const locationLabels: Record<string, { label: string; description: string; color: string }> = {
    'global': { label: 'Global', description: 'Top-level banners and alerts', color: 'bg-amber-50 text-amber-700' },
    'outline-node': { label: 'Outline View', description: 'Icons, badges, alerts on outline nodes', color: 'bg-emerald-50 text-emerald-700' },
    'writing-editor': { label: 'Writing View', description: 'Inline highlights, dots, widgets in the editor', color: 'bg-blue-50 text-blue-700' },
    'right-panel': { label: 'Panel', description: 'Cards, diffs, inputs, threads in the side panel', color: 'bg-indigo-50 text-indigo-700' },
  };

  return (
    <div className="min-h-screen bg-background" style={{ fontSize: '16px' }}>
      <header className="border-b bg-card">
        <div className="max-w-4xl mx-auto px-6 py-6">
          <Link href="/dev" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-3">
            <ArrowLeft className="h-3.5 w-3.5" />
            Developer Reference
          </Link>
          <h1 className="text-2xl font-semibold tracking-tight">Foundation</h1>
          <p className="text-base text-muted-foreground mt-1.5 max-w-2xl leading-relaxed">
            The base layer that all protocols build on: a unified data model and a set of UI primitives.
            Functions produce output; primitives render it. Both sense and negotiate protocols
            compose their entire UI from these primitives.
          </p>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-6 py-8 space-y-12">

        {/* ─── Data Model ─── */}
        <section>
          <h2 className="text-xl font-semibold mb-3">Data Model</h2>
          <p className="text-sm text-muted-foreground mb-4 leading-relaxed max-w-2xl">
            Every function receives a <code className="text-sm bg-muted px-1.5 py-0.5 rounded">DocumentSnapshot</code> — the
            complete current state of the coordination space. Functions don&apos;t fetch data; the platform assembles the snapshot before invocation.
          </p>

          <div className="grid grid-cols-2 gap-4">
            <DataModelCard
              title="Structure Layer"
              subtitle="The coordination space"
              items={[
                { name: 'IntentItem (nodes)', fields: 'id, content, parentId, position, level, createdBy, modifiedBy' },
                { name: 'Dependency', fields: 'fromId, toId, type, label, direction, source, confirmed' },
                { name: 'WritingContent', fields: 'sectionId, html, text, wordCount, paragraphs[]' },
                { name: 'SectionAssignment', fields: 'sectionId, assigneeId, assigneeName' },
                { name: 'DocumentMember', fields: 'userId, name, email, role, joinedAt' },
              ]}
            />
            <DataModelCard
              title="Interaction Layer"
              subtitle="Coordination dynamics"
              items={[
                { name: 'FunctionResult', fields: 'functionId, targetId, output, timestamp' },
                { name: 'Proposal', fields: 'id, pathId, proposerId, changes[], status, votes[]' },
              ]}
            />
          </div>

          <div className="mt-4 border rounded-lg p-4 bg-muted/10">
            <div className="text-sm font-semibold mb-2">DocumentSnapshot</div>
            <pre className="text-sm font-mono text-muted-foreground leading-relaxed">{`{
  documentId, phase, currentUserId,
  nodes: IntentItem[],        // BNA
  dependencies: Dependency[],  // BNA internal relationships
  writing: WritingContent[],   // Individual writing
  assignments: SectionAssignment[],
  members: DocumentMember[],
  functionResults?: StoredFunctionResult[],
  proposals?: Proposal[],
}`}</pre>
          </div>
        </section>

        {/* ─── UI Primitives ─── */}
        <section>
          <h2 className="text-xl font-semibold mb-3">UI Primitives ({primitives.length})</h2>
          <p className="text-sm text-muted-foreground mb-6 leading-relaxed max-w-2xl">
            Primitives are the visual building blocks. Functions declare display bindings that map output
            fields to primitives. The platform resolves templates and renders through PrimitiveRenderer.
            Each primitive has a fixed render location and typed parameters.
          </p>

          {(['global', 'outline-node', 'writing-editor', 'right-panel'] as const).map(location => {
            const prims = byLocation[location] || [];
            const info = locationLabels[location];
            if (prims.length === 0) return null;

            return (
              <div key={location} className="mb-8">
                <div className="flex items-center gap-2 mb-3">
                  <span className={`text-sm font-medium px-2.5 py-1 rounded ${info.color}`}>
                    {info.label}
                  </span>
                  <span className="text-sm text-muted-foreground">{info.description}</span>
                  <span className="text-sm text-muted-foreground ml-auto">{prims.length} primitives</span>
                </div>

                <div className="space-y-3">
                  {prims.map(prim => (
                    <PrimitiveDoc key={prim.type} prim={prim} />
                  ))}
                </div>
              </div>
            );
          })}
        </section>

        {/* ─── Display Bindings ─── */}
        <section>
          <h2 className="text-xl font-semibold mb-3">Display Bindings</h2>
          <p className="text-sm text-muted-foreground mb-4 leading-relaxed max-w-2xl">
            Functions declare how their output maps to primitives using template syntax.
            The platform fills <code className="text-sm bg-muted px-1.5 py-0.5 rounded">{"{{field}}"}</code> templates
            with actual values from function output.
          </p>

          <div className="border rounded-lg p-4 bg-muted/10">
            <pre className="text-sm font-mono text-muted-foreground leading-relaxed">{`// Function output: { alignedIntents: [{id, coverageStatus, coverageNote}], level: 'partial' }

ui: [
  // Iterate over array → one primitive per item
  {
    type: 'node-icon',
    forEach: 'alignedIntents',
    params: {
      nodeId: '{{item.id}}',
      status: '{{item.coverageStatus}}',
      tooltip: '{{item.coverageNote}}',
    },
  },
  // Conditional → only show when condition is true
  {
    type: 'banner',
    when: 'level === "drifted"',
    params: {
      title: 'Drift detected',
      message: '{{summary}}',
      severity: 'warning',
    },
  },
]`}</pre>
          </div>
        </section>
      </div>
    </div>
  );
}

// ─── Components ───

function DataModelCard({ title, subtitle, items }: {
  title: string;
  subtitle: string;
  items: Array<{ name: string; fields: string }>;
}) {
  return (
    <div className="border rounded-lg overflow-hidden">
      <div className="px-4 py-2.5 bg-muted/30 border-b">
        <div className="text-sm font-semibold">{title}</div>
        <div className="text-xs text-muted-foreground">{subtitle}</div>
      </div>
      <div className="divide-y">
        {items.map(item => (
          <div key={item.name} className="px-4 py-2.5">
            <div className="text-sm font-mono font-medium">{item.name}</div>
            <div className="text-sm text-muted-foreground mt-0.5">{item.fields}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

function PrimitiveDoc({ prim }: { prim: PrimitiveDefinition }) {
  const [open, setOpen] = useState(false);
  const preview = PREVIEW_PRIMITIVES[prim.type];

  return (
    <div className="border rounded-lg overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-muted/30 transition-colors"
      >
        {open ? <ChevronDown className="h-4 w-4 text-muted-foreground" /> : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-base font-mono font-medium">{prim.type}</span>
            <span className="text-sm text-muted-foreground">{prim.name}</span>
            {prim.supportsIteration && (
              <span className="text-xs bg-muted text-muted-foreground px-1.5 py-0.5 rounded">forEach</span>
            )}
          </div>
          <div className="text-sm text-muted-foreground mt-0.5">{prim.description}</div>
        </div>
      </button>

      {open && (
        <div className="border-t px-4 py-4 bg-muted/10 space-y-4">
          {/* Parameters */}
          <div>
            <div className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">Parameters</div>
            <div className="space-y-1">
              {prim.params.map(p => (
                <div key={p.key} className="flex items-center gap-2 text-sm">
                  <span className="font-mono font-medium w-28 flex-shrink-0">{p.key}</span>
                  <span className={`font-mono text-xs px-1.5 py-0.5 rounded ${p.required ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}>
                    {p.type}{!p.required && '?'}
                  </span>
                  <span className="text-muted-foreground">{p.description}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Live Preview */}
          {preview && (
            <div>
              <div className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">Preview</div>
              <div className="border rounded-lg p-3 bg-background">
                <PrimitiveRenderer primitives={[preview]} />
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
